pom.xml
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/resources/application.yml
src/test/java/org/folio/marccat/BaseIntegrationTestCase.java

fix configuration

---

src/main/java/org/folio/marccat/Global.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/resources/FieldTemplateAPI.java
src/main/java/org/folio/marccat/resources/RecordTemplateAPI.java

create template from starting BIB record

create template from starting BIB record

---

src/main/java/org/folio/marccat/dao/DAOIndexList.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/SearchAPI.java
src/main/java/org/folio/marccat/search/domain/AbstractRecord.java
src/main/java/org/folio/marccat/search/domain/LightweightJsonRecord.java
src/main/java/org/folio/marccat/search/domain/LightweightVerticalRecord.java
src/main/java/org/folio/marccat/search/domain/MarcRecord.java
src/main/java/org/folio/marccat/search/domain/Record.java
src/main/java/org/folio/marccat/search/engine/ModCatalogingSearchEngine.java
src/main/java/org/folio/marccat/search/engine/SearchEngine.java
src/main/java/org/folio/marccat/search/engine/impl/DefaultModCatalogingSearchEngine.java
src/main/java/org/folio/marccat/search/engine/impl/LightweightModCatalogingSearchEngine.java
src/main/java/org/folio/marccat/search/engine/impl/LightweightVerticalModCatalogingSearchEngine.java

highlight tag function

---

descriptors/ModuleDescriptor-template.json

_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

fix pipeline

---

src/main/java/org/folio/marccat/dao/ClassificationDescriptorDAO.java
src/main/java/org/folio/marccat/dao/ControlNumberDescriptorDAO.java
src/main/java/org/folio/marccat/dao/DAODescriptor.java
src/main/java/org/folio/marccat/dao/NameDescriptorDAO.java
src/main/java/org/folio/marccat/dao/NameTitleDescriptorDAO.java
src/main/java/org/folio/marccat/dao/NameTitleNameDescriptorDAO.java
src/main/java/org/folio/marccat/dao/NameTitleTitleDescriptorDAO.java
src/main/java/org/folio/marccat/dao/PublisherDescriptorDAO.java
src/main/java/org/folio/marccat/dao/PublisherNameDescriptorDAO.java
src/main/java/org/folio/marccat/dao/PublisherPlaceDescriptorDAO.java
src/main/java/org/folio/marccat/dao/PublisherTagDescriptorDAO.java
src/main/java/org/folio/marccat/dao/TitleDescriptorDAO.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/search/TermExpressionNode.java
src/main/java/org/folio/marccat/resources/BrowseAPI.java
src/main/java/org/folio/marccat/resources/domain/HeadingDecorator.java
src/main/java/org/folio/marccat/shared/MapHeading.java

Browse query optimization and SUBSTR function substitution

Browse query optimization and SUBSTR function substitution

---

src/main/java/org/folio/marccat/business/cataloguing/common/Tag.java
src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/dao/DAOIndexList.java
src/main/java/org/folio/marccat/integration/search/BooleanExpressionNode.java
src/main/java/org/folio/marccat/integration/search/Parser.java
src/main/java/org/folio/marccat/integration/search/TermExpressionNode.java
src/main/java/org/folio/marccat/integration/search/Tokenizer.java
src/main/java/org/folio/marccat/model/Subfield.java

Search - Complex query management (using brackets and boolean operators)

Search - Complex query management (using brackets and boolean operators)

---

src/main/java/org/folio/marccat/resources/SearchAPI.java

FOLIO-some fix for merged search

---

src/main/java/org/folio/marccat/dao/CatalogDAO.java
src/main/java/org/folio/marccat/enumaration/CodeListsType.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

fix sonarcloud

---

src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/HeaderTypeAPI.java
src/main/java/org/folio/marccat/resources/domain/HeadingType.java
src/main/java/org/folio/marccat/resources/domain/HeadingTypeCollection.java

merge final changes

---

descriptors/ModuleDescriptor-template.json

fix module descriptor broken

---

Jenkinsfile

added docker step and set to no raml step until finished

added docker step and set to no raml step until finished

---

Jenkinsfile
ramls/marccat.raml

Fix the RAML indentation.
Also enabled lint-raml-cop. The are still some issues with marccat.raml, but now it can assist.

MODCAT-90 raml configuration

---

src/main/java/org/folio/marccat/business/common/PersistenceState.java
src/main/java/org/folio/marccat/dao/CrossReferencesDAO.java
src/main/java/org/folio/marccat/dao/DAODescriptor.java
src/main/java/org/folio/marccat/dao/NameNameTitleReferencesDAO.java
src/main/java/org/folio/marccat/dao/NameTitleDescriptorDAO.java
src/main/java/org/folio/marccat/dao/NameToTitleReferencesDAO.java
src/main/java/org/folio/marccat/dao/TitleNameTitleReferencesDAO.java
src/main/java/org/folio/marccat/dao/persistence/REF.java

Fixed changes of sonarcloud

---

src/main/java/org/folio/marccat/business/cataloguing/authority/AuthorityItem.java
src/main/java/org/folio/marccat/business/cataloguing/bibliographic/BibliographicCatalog.java
src/main/java/org/folio/marccat/business/common/MapBackedSingletonFactory.java
src/main/java/org/folio/marccat/business/common/PersistenceState.java
src/main/java/org/folio/marccat/business/common/UpdateStatus.java
src/main/java/org/folio/marccat/business/common/UserViewHelper.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java
src/main/java/org/folio/marccat/shared/CatalogingInformation.java

fix missing code in create record API

fix missing code in create record API

---

src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

fix error on create record from template

fix error on create record from template

---

src/main/java/org/folio/marccat/business/cataloguing/bibliographic/VariableField.java
src/main/java/org/folio/marccat/business/cataloguing/common/Tag.java
src/main/java/org/folio/marccat/business/cataloguing/common/TagInterface.java
src/main/java/org/folio/marccat/config/Global.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicNoteTag.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicRelationship.java
src/main/java/org/folio/marccat/dao/persistence/NameAccessPoint.java
src/main/java/org/folio/marccat/dao/persistence/NameFunction.java
src/main/java/org/folio/marccat/dao/persistence/NameTitleAccessPoint.java
src/main/java/org/folio/marccat/dao/persistence/NameType.java
src/main/java/org/folio/marccat/dao/persistence/PublisherManager.java
src/main/java/org/folio/marccat/dao/persistence/SubjectAccessPoint.java
src/main/java/org/folio/marccat/dao/persistence/TitleAccessPoint.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java
src/main/java/org/folio/marccat/util/StringText.java

Save record and edit in full_cache

Save record and edit in full_cache

---

src/main/java/org/folio/marccat/resources/HRIDAPI.java
src/main/java/org/folio/marccat/resources/HeadingAPI.java

skeleton api for human readble identifier for [FOLIO-UXPROD-884](https://issues.folio.org/browse/UXPROD-884)

add skeleton HRDI api

---

descriptors/ModuleDescriptor-template.json

fix descriptor for Q4 release

---

script/local/Jenkinsfile
script/local/deploy/deploy_itnet.sh
src/main/java/org/folio/marccat/domain/ConversionFieldUtils.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/search/engine/impl/LightweightModCatalogingSearchEngine.java

test for CD in local env

---

script/local/Jenkinsfile
script/local/deploy/deploy_itnet.sh
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

fix local CI/CD

---

src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/search/Parser.java
src/main/java/org/folio/marccat/integration/search/SQLCommand.java
src/main/java/org/folio/marccat/resources/SearchAPI.java
src/main/java/org/folio/marccat/search/engine/ModCatalogingSearchEngine.java
src/main/java/org/folio/marccat/search/engine/SearchEngine.java

add sort and pagination function

add sort and pagination function

---

src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/integration/search/TermExpressionNode.java
src/main/resources/application.yml

fix script

---

src/main/java/org/folio/marccat/dao/CatalogDAO.java

fix tag 245 on insert record

---

pom.xml
src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/dao/CatalogDAO.java
src/main/java/org/folio/marccat/dao/persistence/CatalogItem.java
src/main/java/org/folio/marccat/integration/search/TermExpressionNode.java

Changes to populate cache table

Changes to populate cache table

---

README.md

update db script

---

src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/dao/DAOBibliographicNoteTag.java
src/main/java/org/folio/marccat/dao/DAOBibliographicRelationship.java

fix delete tag

---

src/main/resources/application.yml
src/main/resources/hibernate.cfg.xml

disable verbose branch for master

disable verbose branch for master

---

src/main/java/org/folio/marccat/dao/CatalogDAO.java

Add note counter when saving the tag

Add note counter when saving the tag

---

pom.xml

Modify dependence

---

pom.xml

change version of postgres-runner

change version of postgres-runner

---

src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/resources/FieldTemplateAPI.java
src/main/java/org/folio/marccat/resources/FixedFieldCodesGroupAPI.java
src/main/java/org/folio/marccat/resources/RecordTemplateAPI.java
src/main/java/org/folio/marccat/resources/domain/FixedFieldCodesGroup.java
src/main/java/org/folio/marccat/resources/shared/FixedFieldUtils.java
src/main/java/org/folio/marccat/resources/shared/RecordUtils.java
src/main/java/org/folio/marccat/resources/shared/ValidationUtils.java
src/main/java/org/folio/marccat/shared/CatalogingInformation.java

remove method from API

---

src/main/java/org/folio/marccat/resources/FixedFieldCodesGroupAPI.java
src/main/java/org/folio/marccat/resources/domain/FixedFieldCodesGroup.java

Add  the headerTypeCode to FixedFieldCodesGroup

Add  the headerTypeCode to FixedFieldCodesGroup

---

src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

Add cataloguingSourceStringText from setup

Add cataloguingSourceStringText from setup

---

src/main/java/org/folio/marccat/integration/StorageService.java

fix category in heading api

---

src/main/java/org/folio/marccat/shared/GeneralInformation.java

remove exception

---

src/main/java/org/folio/marccat/dao/DAOBibItem.java

reset to old exception

---

src/main/java/org/folio/marccat/util/StringText.java

Fix the displayValue a not null for the heading

Fix the displayValue a not null for the heading

---

src/main/java/org/folio/marccat/resources/SearchAPI.java

change api sytnax

---

script/local/mvn/build.sh
src/main/java/org/folio/marccat/config/log/Global.java
src/main/java/org/folio/marccat/dao/common/SessionUtil.java
src/main/java/org/folio/marccat/dao/persistence/PublisherManager.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java
src/main/resources/org/folio/marccat/business/cataloguing/bibliographic/tagFactory.properties
src/main/resources/postgres-conf.json

teporaney 264 fix

---

src/main/java/org/folio/marccat/config/log/Global.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java

Added other publisher codes

---

src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/resources/shared/FixedFieldUtils.java

Fix tag 005

---

src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/dao/DAOBibliographicRelationship.java
src/main/java/org/folio/marccat/dao/common/HibernateUtil.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicRelationship.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicRelationshipTag.java
src/main/resources/application.yml

fix session in API and modify Log

fix session in API and modify Log

---

src/main/java/org/folio/marccat/business/descriptor/SortformUtils.java
src/main/java/org/folio/marccat/dao/persistence/CLSTN.java
src/main/java/org/folio/marccat/dao/persistence/CNTL_NBR.java
src/main/resources/application.yml

fix accent character

---

src/main/java/org/folio/marccat/business/descriptor/SortformUtils.java
src/main/java/org/folio/marccat/dao/persistence/CLSTN.java
src/main/java/org/folio/marccat/dao/persistence/CNTL_NBR.java
src/main/java/org/folio/marccat/integration/search/TermExpressionNode.java

Exclusion sort form for full text search and secondary indexes

Exclusion sort form for full text search and secondary indexes

---

src/main/java/org/folio/marccat/dao/persistence/MaterialDescription.java
src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/integration/StorageService.java

fix update heading except 260, 264

---

src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/search/Parser.java
src/main/java/org/folio/marccat/resources/SearchAPI.java

Fix count search

---

src/main/java/org/folio/marccat/business/cataloguing/bibliographic/BibliographicCatalog.java
src/main/java/org/folio/marccat/domain/ConversionFieldUtils.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/resources/FixedFieldCodesGroupAPI.java
src/main/java/org/folio/marccat/resources/HeadingAPI.java
src/main/java/org/folio/marccat/resources/domain/FixedField.java

Fix tag 007

---

src/main/java/org/folio/marccat/business/cataloguing/common/Tag.java
src/main/java/org/folio/marccat/business/cataloguing/common/TagInterface.java

Fix the skip in filing in full cache table

Fix the skip in filing in full cache table

---

src/main/java/org/folio/marccat/resources/UtilsAPI.java
src/main/java/org/folio/marccat/resources/domain/TagsCollection.java

add extends base class

---

src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/resources/shared/FixedFieldUtils.java

Fix update in full_cache table

Fix update in full_cache table

---

src/main/java/org/folio/marccat/business/cataloguing/bibliographic/BibliographicCatalog.java
src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/domain/ConversionFieldUtils.java
src/main/java/org/folio/marccat/resources/domain/FixedField.java
src/main/java/org/folio/marccat/resources/shared/FixedFieldUtils.java

Fix tag 006-008

---

src/main/java/org/folio/marccat/resources/shared/FixedFieldUtils.java

fix tag 006 visual material

---

src/main/java/org/folio/marccat/integration/RemoteConfiguration.java

Fix limit to configuration

---

src/main/java/org/folio/marccat/integration/record/RecordParser.java

Fix update tag 007, 008, tag nota

---

src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/domain/FilteredTag.java

Fix tag 6XX the second indicator a literal character(C,L,M,N)

Fix tag 6XX the second indicator a literal character(C,L,M,N)

---

src/main/java/org/folio/marccat/business/cataloguing/authority/TimePeriodOfHeading.java
src/main/java/org/folio/marccat/business/cataloguing/bibliographic/VariableHeader.java
src/main/java/org/folio/marccat/business/cataloguing/bibliographic/VariableHeaderUsingItemEntity.java
src/main/java/org/folio/marccat/business/cataloguing/common/Catalog.java
src/main/java/org/folio/marccat/business/cataloguing/common/HeaderFieldHelper.java
src/main/java/org/folio/marccat/business/cataloguing/common/Tag.java
src/main/java/org/folio/marccat/business/cataloguing/common/TagImpl.java
src/main/java/org/folio/marccat/business/cataloguing/common/TimePeriodTag.java
src/main/java/org/folio/marccat/business/common/SubfieldCodeComparator.java
src/main/java/org/folio/marccat/business/common/View.java
src/main/java/org/folio/marccat/dao/BibliographicCatalogDAO.java
src/main/java/org/folio/marccat/dao/PublisherDescriptorDAO.java
src/main/java/org/folio/marccat/dao/common/TransactionalHibernateOperation.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicNote.java
src/main/java/org/folio/marccat/dao/persistence/BibliographicRelationship.java
src/main/java/org/folio/marccat/dao/persistence/Cache.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java
src/main/java/org/folio/marccat/integration/search/SQLCommand.java
src/main/java/org/folio/marccat/shared/Validation.java

Fix the new tag in FULL_CACHE table

Fix the new tag in FULL_CACHE table

---

script/perf/marccat-storagePlan.jmx

start jMeter script

---

descriptors/ModuleDescriptor-template.json

update module descriptor

---

src/main/java/org/folio/marccat/business/cataloguing/bibliographic/BibliographicCatalog.java
src/main/java/org/folio/marccat/business/cataloguing/common/Tag.java
src/main/java/org/folio/marccat/dao/DAODescriptor.java
src/main/java/org/folio/marccat/dao/persistence/NameTitleAccessPoint.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/record/RecordParser.java
src/main/java/org/folio/marccat/resources/BrowseAPI.java
src/main/java/org/folio/marccat/resources/HeadingAPI.java
src/main/java/org/folio/marccat/resources/shared/RecordUtils.java

Fix the type for secondary function code and the add punctuation

Fix the type for secondary function code and the add punctuation

---

src/main/java/org/folio/marccat/dao/DAONameTitleAccessPoint.java

Fix save and delete the tag name title tag

---

pom.xml

fix double library in pom

---

README.md

update and fix readme.md

---

src/main/java/org/folio/marccat/business/common/UpdateStatus.java
src/main/java/org/folio/marccat/dao/persistence/AccessPoint.java
src/main/java/org/folio/marccat/dao/persistence/Unspecified.java
src/main/java/org/folio/marccat/dao/persistence/VideoRecording.java
src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java

Added write configuration on log

Added write configuration on log

---

src/main/java/org/folio/marccat/enumaration/RequestMapping.java
src/main/java/org/folio/marccat/exception/TenantAlreadyExistsException.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/TenantAPI.java
src/main/java/org/folio/marccat/resources/domain/TenantAttributes.java
src/main/resources/application.yml

Add the Tenants management

---

src/main/java/org/folio/marccat/integration/TenantService.java

Added info for log

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/TenantAPI.java

Added other log information

---

src/main/java/org/folio/marccat/integration/TenantService.java

Added other information

---

src/main/java/org/folio/marccat/integration/TenantService.java

Added the file path

---

src/main/java/org/folio/marccat/integration/TenantService.java

added new file path 

---

src/main/java/org/folio/marccat/integration/TenantService.java

Added temporary file

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/TenantAPI.java
src/main/resources/application.yml

Change configurations and write log

Change configurations and write log

---

src/main/java/org/folio/marccat/integration/TenantService.java

Removal of log entries for setup-conf

Removal of log entries for setup-conf

---

src/main/java/org/folio/marccat/config/log/Message.java
src/main/java/org/folio/marccat/integration/TenantService.java

Fix process wait

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/marccat/dao/DAODescriptor.java
src/main/java/org/folio/marccat/dao/NameTitleDescriptorDAO.java
src/main/java/org/folio/marccat/dao/PublisherDescriptorDAO.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/resources/application.yml

Fix pom.xml and search term

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix value Spring boot

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/application.yml

Sql script execution

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix script sql

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/application.yml

Fix scripts sql

---

src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/BrowseAPI.java
src/main/resources/database-setup/init_template.sql

Fix create objects on the database

Fix create objects on the database

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix connection

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix  schema not exist

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix replace variables

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix user_name

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix pgpassword

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix password

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix marccat password

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix the script of the procedure

Fix the script of the procedure

---

src/main/java/org/folio/marccat/integration/TenantService.java

FIX output

---

NEWS.md
pom.xml

tmp-release-1.8.5

---

src/main/resources/application.yml

update parameters 

---

src/main/java/org/folio/marccat/resources/TenantAPI.java

update logger 

---

descriptors/DeploymentDescriptor-template.json
src/main/java/org/folio/marccat/ModMarccat.java

update log for check port

---

src/main/java/org/folio/marccat/ModMarccat.java

test info port

---

src/main/java/org/folio/marccat/ModMarccat.java

fix update

---

descriptors/DeploymentDescriptor-template.json
src/main/java/org/folio/marccat/ModMarccat.java

retry getProprerties

---

descriptors/DeploymentDescriptor-template.json
src/main/java/org/folio/marccat/ModMarccat.java

another attempt

---

descriptors/DeploymentDescriptor-template.json
src/main/java/org/folio/marccat/ModMarccat.java

revert changes

---

src/main/resources/application.yml

change default server port

---

docker/docker-entrypoint.sh

test update

---

src/main/java/org/folio/marccat/integration/TenantService.java

restore createDB

---

Dockerfile

test dockerfile

---

Dockerfile

restore Dockerfile

---

Dockerfile
docker/docker-entrypoint.sh
init.sql

test docker

---

Dockerfile
src/main/java/org/folio/marccat/integration/TenantService.java

test log psql

---

src/main/java/org/folio/marccat/integration/TenantService.java

test update psql path

---

src/main/java/org/folio/marccat/integration/TenantService.java

fix path psql

---

src/main/java/org/folio/marccat/integration/TenantService.java

test hostname

---

src/main/java/org/folio/marccat/integration/TenantService.java

test deploy

---

src/main/java/org/folio/marccat/integration/TenantService.java

test psql commands

---

src/main/java/org/folio/marccat/integration/TenantService.java

test path psql

---

src/main/java/org/folio/marccat/integration/TenantService.java

test path update

---

src/main/java/org/folio/marccat/integration/TenantService.java

update path test

---

src/main/java/org/folio/marccat/integration/TenantService.java

another test

---

src/main/java/org/folio/marccat/integration/TenantService.java

test psql path

---

src/main/java/org/folio/marccat/config/constants/Global.java
src/main/java/org/folio/marccat/integration/OkapiService.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java

Okapi service

---

src/main/java/org/folio/marccat/config/constants/Global.java
src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java

Environment variables

---

src/main/java/org/folio/marccat/integration/TenantService.java

test psql version command

---

src/main/java/org/folio/marccat/integration/TenantService.java

fix test psql 

---

src/main/java/org/folio/marccat/integration/TenantService.java

test psql command path

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/application.yml

another test psql

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/application.yml

retest hostname

---

src/main/java/org/folio/marccat/integration/TenantService.java

test ifconfig

---

src/main/java/org/folio/marccat/integration/TenantService.java

fix ifconfig

---

src/main/java/org/folio/marccat/integration/TenantService.java

retest ifconfig

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix deploy

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix user name

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java
src/main/java/org/folio/marccat/integration/TenantService.java

fix script createObject

---

src/main/java/org/folio/marccat/integration/TenantService.java

fix database

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/database-setup/create-objects_01.sql

fix create object

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java
src/main/java/org/folio/marccat/integration/TenantService.java

Fix script runner

---

src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/resources/database-setup/create-objects_01.sql

update bigFile SQL

---

src/main/java/org/folio/marccat/ModMarccat.java

test address

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

Fix copy index

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix file create_objects

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

Fix function

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

FIX copy line

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

Fix command

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

Fix delimiter

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java
src/main/java/org/folio/marccat/integration/TenantService.java

Fix insert in the s_bib_marc_tag_vldtn table

Fix insert in the s_bib_marc_tag_vldtn table

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java

Restore Script Runner

---

src/main/java/org/folio/marccat/integration/ScriptRunner.java
src/main/java/org/folio/marccat/integration/TenantService.java

Ckeck role

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix database server

---

pom.xml
src/main/java/org/folio/marccat/integration/TenantService.java

Release 1.9.0

---

src/main/java/org/folio/marccat/config/constants/Global.java
src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/TenantAPI.java

Fix okapi client

---

src/main/java/org/folio/marccat/integration/OkapiClient.java

Fix okapiUrl

---

src/main/java/org/folio/marccat/ModMarccat.java
src/main/java/org/folio/marccat/config/constants/Global.java
src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/TenantAPI.java
src/main/resources/application.yml

Fix environment variables

---

src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/resources/TenantAPI.java

Fix Okapi Url

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix database exists

---

src/main/java/org/folio/marccat/integration/Configuration.java
src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java

Fix variables in configuration

Fix variables in configuration

---

src/main/resources/postgres-conf.json

Add postgres-conf.json for defaults

Add postgres-conf.json for defaults

---

descriptors/DeploymentDescriptor-environment-template.json
descriptors/DeploymentDescriptor-template.json

Fix external database

---

descriptors/DeploymentDescriptor-template.json
src/main/resources/postgres-conf.json

Fix deployment

---

descriptors/ModuleDescriptor-template.json

Fix permission

---

src/main/java/org/folio/marccat/resources/SearchAPI.java

Fix Search API

---

src/main/java/org/folio/marccat/integration/Configuration.java
src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/integration/OkapiClient.java
src/main/java/org/folio/marccat/integration/RemoteConfiguration.java
src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/resources/SearchAPI.java

Fix url okapi

---

src/main/java/org/folio/marccat/integration/TenantService.java

Fix end point

---

src/main/java/org/folio/marccat/integration/TenantService.java
src/main/java/org/folio/marccat/integration/search/BooleanExpressionNode.java

fix create-object

---

NEWS.md
pom.xml
src/main/java/org/folio/marccat/integration/OkapiClient.java

Release-2.0.0

---

NEWS.md
pom.xml
src/main/java/org/folio/marccat/integration/MarccatHelper.java

Release-v2.1.5

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/marccat/integration/OkapiClient.java

Fix permissions

---

descriptors/ModuleDescriptor-template.json

Fix descriptor

---

descriptors/ModuleDescriptor-template.json

fix version for ui release

---

NEWS.md
pom.xml
src/main/java/org/folio/marccat/integration/TenantService.java

Release v2.2.5

---

src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

Fix response

---

src/main/java/org/folio/marccat/integration/MarccatHelper.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java

Fix double headers

---

src/main/java/org/folio/marccat/integration/MarccatHelper.java

Fix headers

---

descriptors/ModuleDescriptor-template.json

increase memory

---

descriptors/ModuleDescriptor-template.json

See https://dev.folio.org/guides/module-descriptor/#launchdescriptor-properties

Increase container memory

---

src/main/java/org/folio/marccat/integration/StorageService.java

Fix browse

---

descriptors/ModuleDescriptor-template.json

decrease memory

---

src/main/java/org/folio/marccat/integration/tools/TenantLoading.java

fix import

---

src/main/java/org/folio/marccat/resources/TenantAPI.java

Fix sample

---

src/main/java/org/folio/marccat/dao/persistence/PublisherManager.java
src/main/java/org/folio/marccat/integration/record/BibliographicInputFile.java
src/main/java/org/folio/marccat/integration/tools/TenantLoading.java
src/main/java/org/folio/marccat/resources/TenantAPI.java

Fix tag 260

---

src/main/java/org/folio/marccat/dao/SemanticDAO.java

Fix MODCAT-164 and refactoring

Fix MODCAT-164 and refactoring

---

src/main/java/org/folio/marccat/dao/GlobalVariableDAO.java

Fix MODCAT-165

---

descriptors/ModuleDescriptor-template.json

See [MODCAT-200](https://issues.folio.org/browse/MODCAT-200)
Empty permissionsRequired array enables [FOLIO-2633](https://issues.folio.org/browse/FOLIO-2633) to proceed.
Proper permissions needed later.

MODCAT-200 Add temporary default permissionsRequired

---

src/main/java/org/folio/marccat/dao/common/TransactionalHibernateOperation.java

Fix merged

---

src/main/java/org/folio/marccat/dao/BibliographicNoteTagDAO.java
src/main/java/org/folio/marccat/dao/BibliographicValidationDAO.java
src/main/java/org/folio/marccat/dao/IndexListDAO.java
src/main/java/org/folio/marccat/dao/PublTagDAO.java
src/main/java/org/folio/marccat/dao/ValidationDAO.java
src/main/java/org/folio/marccat/dao/persistence/PUBL_TAG.java

FIX Sonar and DAO

---

descriptors/ModuleDescriptor-template.json

Fix client version 3.0 of marccat

Fix client version 3.0 of marccat

---

descriptors/ModuleDescriptor-template.json

Fix version

---

src/main/java/org/folio/marccat/resources/AuthorityRecordAPI.java
src/main/java/org/folio/marccat/resources/domain/ContainerRecordTemplate.java
src/test/resources/authority/geographic.json
src/test/resources/authority/name.json
src/test/resources/authority/subject.json
src/test/resources/authority/title.json

MODCAT-210: Create authority from json
Changed the received json to adapt it to the ui

MODCAT-210: Create authority from json

---

src/main/java/org/folio/marccat/integration/TenantRefService.java
src/main/java/org/folio/marccat/integration/tools/TenantLoading.java
src/main/java/org/folio/marccat/resources/TenantAPI.java

MODCAT-223: mod-marccat throws 500 error on tenant initialization
When a sample data json is not found, the error thrown is handled

MODCAT-223: mod-marccat throws 500 error on tenant initialization

---

src/main/java/org/folio/marccat/integration/TenantRefService.java
src/test/java/org/folio/marccat/resources/TenantTest.java

Load bibliographic sample by default

MODCAT-207 Load authority sample data

---

src/main/java/org/folio/marccat/resources/shared/ConversionFieldUtils.java

Fix error because of the spaces of 008

MODCAT-217: Create an API for set the display value for authority 008 tag

---

src/main/java/org/folio/marccat/business/cataloguing/authority/AuthorityTagImpl.java
src/main/java/org/folio/marccat/dao/AuthorityCorrelationDAO.java
src/main/java/org/folio/marccat/dao/BibliographicCorrelationDAO.java
src/main/java/org/folio/marccat/integration/StorageService.java
src/main/java/org/folio/marccat/resources/AuthorityRecordAPI.java
src/main/java/org/folio/marccat/resources/BibliographicRecordAPI.java
src/main/java/org/folio/marccat/resources/HeadingAPI.java
src/main/java/org/folio/marccat/resources/shared/RecordUtils.java
src/test/java/org/folio/marccat/resources/HeadingTest.java
src/test/resources/authority/headingName.json

MODCAT-210: Create authority from json
Create a heading from authority record

Uxprod 2627
